spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        - id: useService
          uri: lb://USESERVICE
          predicates:
            - Path=/users/**
        - id: productService
          uri: lb://PRODUCTSERVICE
          predicates:
            - Path=/products/**
        - id: orderService
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/orders/**
      default-filters:
        - StripPrefix=0
  web:
    resources:
      add-mappings: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
  instance:
    preferIpAddress: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG