spring:
  application:
    name: ServiceDiscovery

  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
