spring:
  application:
    name: AuthService

  datasource:
    url: jdbc:mysql://localhost:3306/poc_schema
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8084

logging:
  level:
    root: INFO